### PR TITLE
fix gatsby-theme-apollo readme link

### PR DESCRIPTION
**Pull request by mckelveygreg**
The old link was broken.
However, I'm not sure which link you wanted it to go to. 
I took a guess and sent it here: https://github.com/apollographql/gatsby-theme-apollo

Thanks for your plugin!!

### CODE REVIEW

**Comment by trevorblades** [comment]
Good catch @mckelveygreg! Could you just change the link to `https://github.com/apollographql/gatsby-theme-apollo/tree/master/packages/gatsby-theme-apollo` instead?

**Review by trevorblades — CHANGES_REQUESTED** [review]
Good catch @mckelveygreg! I was originally trying to link to the specific package within that monorepo. Could you just change the link to https://github.com/apollographql/gatsby-theme-apollo/tree/master/packages/gatsby-theme-apollo instead?

Looks good to merge once that's done 👍

**Comment by mckelveygreg** [comment]
no problem. 
Just noticed today that this PR never closed!
Thanks again!

**Review by trevorblades — APPROVED** [review]

**Comment by trevorblades** [comment]
Thanks @mckelveygreg!

**Pull request merged**
